DROP TABLE IF EXISTS clerk;

CREATE TABLE IF NOT EXISTS clerk (
  id INT AUTO_INCREMENT,
  name TEXT NOT NULL,
  created_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);